# Generated by Django 5.0.3 on 2024-04-13 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approval2',
            name='project',
        ),
        migrations.RemoveField(
            model_name='entryinformation',
            name='project',
        ),
        migrations.RemoveField(
            model_name='extraquestions',
            name='project',
        ),
        migrations.RemoveField(
            model_name='reports',
            name='project',
        ),
        migrations.DeleteModel(
            name='Approval1',
        ),
        migrations.DeleteModel(
            name='Approval2',
        ),
        migrations.DeleteModel(
            name='EntryInformation',
        ),
        migrations.DeleteModel(
            name='ExtraQuestions',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='Reports',
        ),
    ]
